# Generated by Django 3.2.5 on 2021-07-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('over18', models.BooleanField()),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('createpass', models.CharField(max_length=20)),
                ('confirmpass', models.CharField(max_length=20)),
            ],
        ),
    ]
